apiVersion: v2
name: users-app-chart
description: A Helm chart for OTUS test app


type: application
version: 1.0.6
appVersion: "prometheus-app-v05"


dependencies:
  - name: postgresql
    version: 8.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
    tags:
      - users-app-database
