apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: "student-app-student-app-ingress"
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - host: arch.homework
      http:
        paths:
          - path: /(\w+)/(.*)
            backend:
              serviceName: "student-app-student-app-service"
              servicePort: {{ .Values.service.port }}
