apiVersion: skaffold/v2beta12
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - image: auth-app
    context: .
deploy:
  helm:
    releases:
    - name: auth-app
      chartPath: auth-chart
      skipBuildDependencies: true
      values:
        image: auth-app
