apiVersion: v1
kind: Service
metadata:
  name: student-app-service
spec:
  selector:
    app: student-app
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 80
      nodePort: 30081
  type: NodePort
