apiVersion: v2
name: idempotency-app-chart
description: A Helm chart for OTUS test app


type: application
version: 1.2.5
appVersion: "idempotency-app-v29"


dependencies:
  - name: postgresql
    version: 8.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
    tags:
      - idempotency-app-database
