apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.services.orders.name }}-service"
  labels:
    {{- include "kafka-app-chart.labels" . | nindent 4 }}

spec:
  selector:
    app: "{{ .Values.services.orders.name }}-{{ .Chart.AppVersion }}"
  type: {{ .Values.services.orders.type }}
  ports:
    - name: "{{ .Values.services.orders.name }}-web"
      port: {{ .Values.services.orders.port }}
      targetPort: http
      protocol: TCP


---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.services.billing.name }}-service"
  labels:
    {{- include "kafka-app-chart.labels" . | nindent 4 }}

spec:
  selector:
    app: "{{ .Values.services.billing.name }}-{{ .Chart.AppVersion }}"
  type: {{ .Values.services.billing.type }}
  ports:
    - name: "{{ .Values.services.orders.name }}-web"
      port: {{ .Values.services.billing.port }}
      targetPort: http
      protocol: TCP


---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.services.notify.name }}-service"
  labels:
    {{- include "kafka-app-chart.labels" . | nindent 4 }}

spec:
  selector:
    app: "{{ .Values.services.notify.name }}-{{ .Chart.AppVersion }}"
  type: {{ .Values.services.notify.type }}
  ports:
    - name: "{{ .Values.services.orders.name }}-web"
      port: {{ .Values.services.notify.port }}
      targetPort: http
      protocol: TCP
