apiVersion: v1
kind: ConfigMap
metadata:
  name: users-app-config
data:
  DB_DRIVER: "postgresql"
  DB_HOST: {{ include "postgresql.fullname" . | quote }}
  DB_PORT: {{ .Values.postgresql.service.port | quote }}
  DB_NAME: {{ .Values.postgresql.postgresqlDatabase | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: users-app-secret
type: Opaque
data:
  DB_USERNAME: {{ .Values.postgresql.postgresqlUsername | b64enc | quote }}
  DB_PASSWD: {{ .Values.postgresql.postgresqlPassword | b64enc | quote }}
