{
 "title": "IncomingRequests",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Incoming Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum( rate( incoming_requests{ path =~ \"/a/.*/\", method = \"GET\" }[3m] ) )"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) ( rate( response_time_bucket{ path =~ \"/a/.+/\", method = \"GET\" }[3m] ) )) * 1000"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) ( rate( response_time_bucket{ path =~ \"/a/.+/\", method = \"GET\" }[3m] ) )) * 1000"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) ( rate( response_time_bucket{ path =~ \"/a/.+/\", method = \"GET\" }[3m] ) )) * 1000"
    }
   ]
  },
  {
   "title": "Response Codes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum( rate( response_code{ path =~ \"/a/.*/\", method = \"GET\", code =~ \"2.+\" }[3m] ) )"
    },
    {
     "expr": "sum( rate( response_code{ path =~ \"/a/.*/\", method = \"GET\", code =~ \"5.+\" }[3m] ) )"
    }
   ]
  },
  {
   "title": "RAM consume",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum( container_memory_usage_bytes{ pod =~ \"users-app-users-app-chart-.+\" } / 1000000 )"
    }
   ]
  },
  {
   "title": "CPU consume",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate( container_cpu_usage_seconds_total{ pod =~ \"users-app-users-app-chart-.+\" }[3m] )"
    }
   ]
  }
 ]
}